version: '3.8'
services:
  sqlite3:
    image: sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - "./db/:/root/db/"
  
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    depends_on:
      - sqlite3
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - app
    environment:
      - RAILS_MASTER_KEY=27e3a2700abbb8da46ee1bc5d54d74ff
    ports:
      - 80:80
