version: '3.8'
services:
  sqlite3:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - "./db/:/root/db/"

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    entrypoint: ["/app/lib/docker-entrypoint.sh"]
    command: bash -c "RAILS_ENV=production bundle exec puma -C config/puma.rb"
    environment:
      - RAILS_MASTER_KEY=27e3a2700abbb8da46ee1bc5d54d74ff
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - sqlite3
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - app
    environment:
      - RAILS_MASTER_KEY=27e3a2700abbb8da46ee1bc5d54d74ff
    ports:
      - 80:80